### ISSUE TITLE
eebiic_estimateのエラー

### ISSUE THREAD

**Issue by y-naka** [metagen/EEBIIC#4]
EEBIICを実行した結果、以下のようなエラーが発生。

実行したコマンド
```bash
eebiic_estimate     "${WORKING_DIR}/eebiic_out/result"     "${WORKING_DIR}/eebiic_out/interval_data"
```

エラー
```bash
INFO:eebiic.estimate:Start MCMC sampling
misc.py:399: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif np.issubdtype(np.asarray(v).dtype, float):
Traceback (most recent call last):
  File "eebiic_estimate", line 11, in <module>
    load_entry_point('eebiic==1.0.0', 'console_scripts', 'eebiic_estimate')()
  File "estimate.py", line 191, in main_wrapper
    main(logger=get_logger(__name__), **argument_parse())
  File "estimate.py", line 162, in main
    n_jobs=n_jobs)
  File "model.py", line 672, in sampling
    fit = self.fit_class(data, seed)
  File "stanfit4freq5_cf3de1bab4492d4d44aec0061f226b36_7599189618614517591.pyx", line 459, in stanfit4freq5_cf3de1bab4492d4d44aec0061f226b36_7599189618614517591.StanFit4Model.__cinit__
ValueError: Exception: freq5_cf3de1bab4492d4d44aec0061f226b36_namespace::freq5_cf3de1bab4492d4d44aec0061f226b36: SubjectID[k0__] is 42, but must be less than or equal to 40  (in 'unknown file name' at line 4)
```

**Comment by suzuki-shm** [comment]
Subject IDが切り詰められて居ないようです。
たぶん、いくつか脱落データがあって、1,2,3,4,6,……みたいに抜けているのがありませんか？それは許可されません。ユニークなSubjectIDが40しかないのに、SubjectID=42があるのでエラーが吐かれています。

あとこのリポジトリはクローズじゃないので、色々と情報が漏れて、その書き方は良くないと思いますよ。Closeしても残ってしまうので、metagenグループのadmin権限がある人のアカウントでIssue自体を消したほうがいいと思います。
